### ISSUE TITLE
Release tagging

### ISSUE THREAD

**Issue by electrickite** [grawity/tpm_futurepcr#3]
Would you consider continuing to tag stable releases?

It would be great to be able to create distribution packages of stable versions.

**Comment by grawity** [comment]
Yeah, I should do that – but it probably requires a more specific goal than "it hasn't crashed for a while on my system"...

I've tagged v1.2 now though (and apparently it just now pushed the v1.1 tag as well).

**Comment by electrickite** [comment]
Thanks, appreciate it!

For projects I maintain, I try to stick to semantic versioning. Usually try to bump the minor version when a new feature is introduced, patch version for bug fixes or internal improvements. Major version is increased when I need to push a breaking change of some kind.
